<?php
DEFINE("HOST","localhost");
DEFINE("ROOT","root");
DEFINE("PASS","");
DEFINE("EMAIL_PORT",465);
DEFINE("EMAIL_HOST","smtp.gmail.com");
DEFINE("EMAIL_USERNAME","");
DEFINE("EMAIL_PASSWORD","");
DEFINE("PROJECT_TITLE", "MY PROJECT");
DEFINE("DATABASE","database");
DEFINE("USER_TABLE","users");
DEFINE("BASEURL","localhost/");
DEFINE("API_KEY","");

DEFINE("SMS_API_KEY","");
DEFINE("SMS_API_NAME","");
?>